fos_rest:
  body_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  exception:
    enabled: true
    messages:
      { App\Exception\CustomException: true , Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true }
    codes:
      { App\Exception\CustomException: 401 , Symfony\Component\HttpKernel\Exception\BadRequestHttpException: 400 }