security:
    encoders:
        App\Entity\User:
            algorithm: argon2id

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        doc:
            pattern: ^/doc
            security: false
        main:
            pattern: ^/api
            stateless: true
            anonymous: false
            guard:
                authenticators:
                    - App\Security\JwtAuthenticator

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
